apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bvgaurav/lol:latest  
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure